# Generated by Django 3.0.8 on 2020-10-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Puffin',
        ),
    ]
