# Generated by Django 3.0.8 on 2020-10-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201006_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fish', models.CharField(choices=[('E', 'Eels'), ('H', 'Herring'), ('C', 'Capelin'), ('S', 'Crustaceans')], default='E', max_length=1)),
                ('puffin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Puffin')),
            ],
        ),
    ]
